name: 'Proxmox OpenAPI artifacts'
description: 'Generate Proxmox OpenAPI outputs via the automation pipeline.'
author: 'Proxmox API maintainers'
inputs:
  mode:
    description: 'Execution mode to pass to the automation pipeline (ci|full).'
    required: false
    default: 'ci'
  base-url:
    description: 'Override base URL for the Proxmox API viewer scrape.'
    required: false
  raw-snapshot-path:
    description: 'Location for the persisted raw snapshot JSON.'
    required: false
  ir-output-path:
    description: 'Destination path for the normalized intermediate representation.'
    required: false
  openapi-dir:
    description: 'Directory to write OpenAPI artifacts.'
    required: false
  openapi-basename:
    description: 'Basename for generated OpenAPI files.'
    required: false
  fallback-to-cache:
    description: 'Allow the pipeline to reuse cached snapshots when scrapes fail (CI default).'
    required: false
    default: 'true'
  offline:
    description: 'Force offline mode (skip live scrape).'
    required: false
    default: 'false'
  install-command:
    description: 'Command used to install dependencies before running the pipeline.'
    required: false
    default: 'npm ci'
  working-directory:
    description: 'Repository subdirectory that contains package.json and automation sources.'
    required: false
    default: '.'
  install-playwright-browsers:
    description: 'Install Playwright browser dependencies before running the pipeline.'
    required: false
    default: 'true'
  report-path:
    description: 'Optional path to write the pipeline summary JSON.'
    required: false
  extra-cli-args:
    description: 'Deprecated. The TypeScript action ignores this input.'
    required: false
  node-version:
    description: 'Deprecated. Configure Node via actions/setup-node in the workflow.'
    required: false
outputs:
  raw-snapshot:
    description: 'Absolute path to the raw snapshot JSON used by the pipeline.'
  normalized-document:
    description: 'Absolute path to the normalized IR document.'
  openapi-json:
    description: 'Absolute path to the generated OpenAPI JSON file.'
  openapi-yaml:
    description: 'Absolute path to the generated OpenAPI YAML file.'
  from-cache:
    description: 'Whether the pipeline reused an existing cached snapshot.'
  summary-path:
    description: 'Path to the JSON summary describing the pipeline run.'
runs:
  using: "composite"
  steps:
    - name: Run Proxmox OpenAPI automation pipeline
      shell: bash
      env:
        INPUT_MODE: ${{ inputs.mode }}
        INPUT_BASE_URL: ${{ inputs.base-url }}
        INPUT_RAW_SNAPSHOT_PATH: ${{ inputs.raw-snapshot-path }}
        INPUT_IR_OUTPUT_PATH: ${{ inputs.ir-output-path }}
        INPUT_OPENAPI_DIR: ${{ inputs.openapi-dir }}
        INPUT_OPENAPI_BASENAME: ${{ inputs.openapi-basename }}
        INPUT_FALLBACK_TO_CACHE: ${{ inputs.fallback-to-cache }}
        INPUT_OFFLINE: ${{ inputs.offline }}
        INPUT_INSTALL_COMMAND: ${{ inputs.install-command }}
        INPUT_WORKING_DIRECTORY: ${{ inputs.working-directory }}
        INPUT_INSTALL_PLAYWRIGHT_BROWSERS: ${{ inputs.install-playwright-browsers }}
        INPUT_REPORT_PATH: ${{ inputs.report-path }}
        INPUT_EXTRA_CLI_ARGS: ${{ inputs.extra-cli-args }}
        INPUT_NODE_VERSION: ${{ inputs.node-version }}
      run: |
        set -euo pipefail
        node .github/actions/proxmox-openapi-artifacts/main.mjs
branding:
  icon: 'server'
  color: 'green'
